[package]
name = "bench_diff"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "Reliably compare the latency difference between two functions/closures."
repository = "https://github.com/pvillela/rust-bench-diff/tree/main"
documentation = "https://docs.rs/bench_diff/latest/bench_diff/"
readme = "README.md"
keywords = [
    "latency",
    "measurement",
    "performance",
    "benchmarking",
    "difference",
]
categories = ["development-tools::profiling"]
exclude = ["CHANGELOG.md", "*.sh", ".gitignore"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hdrhistogram = "7.5"
regex = "1"          # only used by bin
statrs = "0.18"
