[package]
name = "dev_support"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
rand = "0.8"
# thread_local_collect = { git = "https://github.com/pvillela/rust-thread-local-collect", tag = "v0.5.0" }
thread_local_collect = { path = "../../thread-local-collect" }
futures = "0.3"
